services:
    db:
        image: postgres:15
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test_db
        ports:
            - 5432:5432